main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.Index.as_view(), name = 'index'),
    path('restaurants/', views.RestaurantList.as_view(), name = 'restaurants'),
    path('restaurant/<int:pk>', views.RestaurantDetail.as_view(), name = 'restaurant'),
    path('add_restaurant/', views.CreateRestaurant.as_view(), name = 'add_restaurant'),
    path('edit_restaurant/<int:pk>', views.UpdateRestaurant.as_view(), name = 'edit_restaurant'),
    path('delete_restaurant/<int:pk>', views.DeleteRestaurant.as_view(), name = 'delete_restaurant'),

    path('food/<int:pk>', views.FoodDetail.as_view(), name = 'food'),
]

zomato/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length = 100)
    closing_time = models.TimeField(null = True, blank = True)
    owner = models.CharField(max_length = 100, null = True, blank = True)
    contact = models.EmailField()
    address = models.TextField()

    def __str__(self):
        return self.name

class Food(models.Model):
    CUISINE = (
        (1, 'Chinese'),
        (2, 'North Indian'),
        (3, 'South Indian'),
        (4, 'Italian'),
    )

    name = models.CharField(max_length = 100)
    price = models.FloatField()
    cuisine = models.IntegerField(choices = CUISINE)
    restaurant = models.ForeignKey('Restaurant', on_delete = models.CASCADE)

    def __str__(self):
        return self.name
    

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from main import models

# Create your views here.

class Index(TemplateView):
    template_name = 'main/index.html'

# def index(request):
#     context = {}
#     return render(request, 'main/index.html', context)

class RestaurantList(ListView):
    model = models.Restaurant
    context_object_name = 'restaurants'
    # queryset = models.Restaurant.objects.filter(name__contains = 'd')

# def restaurants(request):
#     restaurants = models.Restaurant.objects.all()

#     context = {
#         'restaurants': restaurants
#     }
#     return render(request, 'main/restaurants.html', context)

class RestaurantDetail(DetailView):
    model = models.Restaurant
    template_name = 'main/restaurant.html'
    context_object_name = 'restaurant'

# def restaurant(request, pk):
#     # try:
#     #     restaurant = models.Restaurant.objects.get(pk = pk)
#     # except:
#     #     raise Http404
#     restaurant = get_object_or_404(models.Restaurant, pk=pk)

#     context = {
#         'restaurant': restaurant
#     }
#     return render(request, 'main/restaurant.html', context)

class FoodDetail(DetailView):
    model = models.Food

# def food(request, pk):
#     food = get_object_or_404(models.Food, pk=pk)

#     context = {
#         'food': foods
#     }
#     return render(request, 'main/food.html', context)

class CreateRestaurant(CreateView):
    model = models.Restaurant
    success_url = reverse_lazy('restaurants')
    # success_url = '/restaurants/'
    fields = '__all__'

class UpdateRestaurant(UpdateView):
    model = models.Restaurant
    success_url = reverse_lazy('restaurants')
    fields = '__all__'

class DeleteRestaurant(DeleteView):
    model = models.Restaurant
    success_url = reverse_lazy('restaurants')

templates/main/food_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>{{ object.name }}</h1>

        <!-- CUISINE = (
            (1, 'Chinese'),
            (2, 'North Indian'),
            (3, 'South Indian'),
            (4, 'Italian'),
        )

        name = models.CharField(max_length = 100)
        price = models.FloatField()
        cuisine = models.IntegerField(choices = CUISINE)
        restaurant = models.ForeignKey('Restaurant', on_delete = models.CASCADE) -->

        <ul>
            <li>Price: {{ object.price }}</li>
            <li>Cuisune: {{ object.get_cuisine_display }}</li>
        </ul>
    </body>
</html>

templates/main/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Page Title</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" media="screen" href="main.css" />
		<script src="main.js"></script>
	</head>
	<body>
		<h1>Welcome to Zomato</h1>

		<h4>Navigation</h4>
		<ul>
			<li><a href="{% url 'restaurants' %}">All Restaurants</a></li>
		</ul>
	</body>
</html>

templates/main/restaurant.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>

        <ul>
            <li><a href="{% url 'edit_restaurant' pk=restaurant.pk %}">Edit</a></li>
            <li><a href="{% url 'delete_restaurant' pk=restaurant.pk %}">Delete</a></li>
        </ul>

        <h1>{{ restaurant.name }}</h1>

        <p>
            Closing Time: {{ restaurant.closing_time }} <br>
            Owner: {{ restaurant.owner }} <br>
            Contact: {{ restaurant.contact }} <br>
            Address: {{ restaurant.address }}
        </p>

        <h3>Menu</h3>

        <ul>
            {% for food in restaurant.food_set.all %}
                <li>
                    <a href="{% url 'food' pk=food.pk %}">{{ food }}</a>
                </li>
            {% endfor %}
        </ul>
    </body>
</html>

templates/main/restaurant_confirm_delete.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <form action="" method="post">
            {% csrf_token %}
            Are you sure you want to delete?
            <button type="submit" value="confirm">Delete</button>
        </form>
    </body>
</html>

templates/main/restaurant_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>Add Restaurant</h1>

        <form action="" method="post">
            {% csrf_token %}

            {{ form }}

            <button type="submit">Submit</button>
        </form>
    </body>
</html>

templates/main/restaurant_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script>
    </head>
    <body>
        <h1>Restaurants</h1>

        <ul>
            {% for restaurant in restaurants %}
                <li>
                    <a href="{% url 'restaurant' pk=restaurant.pk %}">{{ restaurant }}</a>
                </li>
            {% endfor %}
        </ul>
    </body>
</html>